from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from chatterbot import comparisons,response_selection
def chatbot():
    bot = ChatBot(
        "buddy",
    logic_adapters=[
        'chatterbot.logic.BestMatch'
        ],
    read_only=True)
    #storage_adapter="chatterbot.storage.SQLStorageAdapter",)
    #database_uri="sqlite:///database.sqlalchemy")


    trainer = ListTrainer(bot)
    trainer.train([
    "hi",
    "Hello, how can i help you",
    "hello",
    "Hi, How can i help you",
    "cool",
    "yup",
    "ok",
    "Yup",
    "okay",
    "Yeah",
    "yup",
    "Okay",
    "yeah",
    "Okies",
    "okay thanks",
    "No Problem! Have a Good Day!",
    "dont want to share",
    "No Problem",
    "bye",
    "Bye, Take Care",
    "bye",
    "Bye, Stay Safe",
    "take care",
    "Yup, Stay Safe",
    "hmm",
    "Yup",
    "sure",
    "yup",
    "will be waiting",
    "Sure",
    "hi how are you",
    "I'm fine, Thank you. How about you",
    "how are you",
    "I'm great, How about you",
    "im fine",
    "That's nice",
    "whats your age",
    "Hypothtical question",
    "im fine too",
    "Great",
    "im great",
    "Good",
    "im great too",
    "That's really good to hear",
    "im also fine",
    "That's good to hear",
    "im also great",
    "thats great",
    "whats up",
    "You have to say",
    "wats up",
    "you have to say",
    "what is your name",
    "My name is Disha, Virtual assistant of Tamak's foundation",
    "whats your name",
    "My name is Disha, Virtual assistant of Tamak's foundation",
    "whats ur name",
    "My name is Disha, Virtual assistant of Tamak's foundation",
    "wats ur name",
    "My name is Disha, Virtual assistant of Tamak's foundation",
    "fine",
    "good",
    "great",
    "Yup",
    "thats cool",
    "Yeah",
    "cool",
    "Hmmm",
    "why should i share",
    "Okay, No Problem",
    "dont want to share",
    "It's Okay",
    "sure",
    "Okay",
    "sure",
    "Yup",
    "thanks",
    "No, Problem",
    "sure thanks",
    "No worries"
    ])
    return bot